spring:
    devtools:
        restart:
            enabled: true
    jackson:
        serialization.indent_output: true
        serialization.write_dates_as_timestamps: false
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:file:./target/h2db/db/doorbell;DB_CLOSE_DELAY=-1
        username: doorbell
        password:
    h2:
        console:
            enabled: false
    jpa:
        open-in-view: false
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        show-sql: false
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    mail:
        host: localhost
        port: 25
        username:
        password:
    thymeleaf:
        cache: false
server:
    port: 8080
